# Generated by Django 5.0.2 on 2024-03-11 16:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationPlanning',
            fields=[
                ('adminplanid', models.AutoField(primary_key=True, serialize=False)),
                ('is_land_surveyed', models.BooleanField(blank=True, null=True)),
                ('parcel_under_use', models.BooleanField(blank=True, null=True)),
                ('type_of_use', models.CharField(blank=True, choices=[('Commercial Residential', 'Commercial Residential'), ('Personal residential', 'Personal residential'), ('Commercial', 'Commercial'), ('Offices', 'Offices'), ('Institutional', 'Institutional'), ('Industrial', 'Industrial'), ('Agricultural', 'Agricultural'), ('Recreational', 'Recreational'), ('Other', 'Other')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'administration_planning',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('infraid', models.AutoField(primary_key=True, serialize=False)),
                ('water_supply', models.CharField(blank=True, choices=[('1', 'Personal Piped supply'), ('2', 'Local government piped supply'), ('3', 'Community piped supply'), ('4', 'Water tanks'), ('5', 'Borehole'), ('6', 'Well'), ('7', 'River/spring'), ('8', 'Others')], max_length=100, null=True)),
                ('electricalpower', models.CharField(blank=True, choices=[('1', 'National grid'), ('2', 'Solar energy'), ('3', 'Others')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'infrastructure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('no_of_children', models.IntegerField(blank=True, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('ownershipid', models.AutoField(primary_key=True, serialize=False)),
                ('mode_of_acquisition', models.CharField(blank=True, choices=[('1', 'Inheritance'), ('2', 'Government allocation'), ('3', 'County council allocation'), ('4', 'First acquisition'), ('5', 'No idea how the land was acquired'), ('6', 'Others')], max_length=100, null=True)),
                ('ownership_type', models.CharField(blank=True, choices=[('1', 'Leasehold'), ('2', 'Freehold'), ('3', 'Allotment'), ('4', 'Community land'), ('5', 'Others')], max_length=100, null=True)),
                ('lease_duration_from', models.DateField(blank=True, null=True)),
                ('lease_duration_to', models.DateField(blank=True, null=True)),
                ('pay_landrates', models.BooleanField(blank=True, null=True)),
                ('proof_of_ownership', models.BooleanField(blank=True, null=True)),
                ('type_of_document', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ownership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('plot_number', models.IntegerField(primary_key=True, serialize=False)),
                ('parcel_area', models.FloatField(blank=True, null=True)),
                ('allocation_number', models.CharField(blank=True, db_column='Allocation_Number', max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'plots',
                'managed': False,
            },
        ),
    ]
