# Generated by Django 5.0.2 on 2024-03-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makutano', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plots',
            options={'managed': False, 'verbose_name_plural': 'plots'},
        ),
    ]
