# Generated by Django 5.0.2 on 2024-03-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makutano', '0002_alter_plots_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrationplanning',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ownership',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plots',
            options={'managed': True, 'verbose_name_plural': 'plots'},
        ),
    ]
